disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string

included:
  - OrMiMu
  - OrMiMuTests
  - OrMiMuUITests

excluded:
  - Pods
  - Carthage
  - Package.swift

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 1000
  error: 1500

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"
