name: OrMiMu
options:
  bundleIdPrefix: com.kyberix
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
settings:
  base:
    ENABLE_HARDENED_RUNTIME: YES
    SWIFT_STRICT_CONCURRENCY: complete
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  OrMiMu:
    type: application
    platform: macOS
    sources:
      - path: OrMiMu
    settings:
      INFOPLIST_FILE: OrMiMu/Info.plist
      CODE_SIGN_ENTITLEMENTS: OrMiMu/OrMiMu.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: com.kyberix.OrMiMu
      COMBINE_HIDPI_IMAGES: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    postBuildScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint
    scheme:
      testTargets:
        - OrMiMuTests
        - OrMiMuUITests
  OrMiMuTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: OrMiMuTests
    dependencies:
      - target: OrMiMu
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.kyberix.OrMiMuTests
  OrMiMuUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: OrMiMuUITests
    dependencies:
      - target: OrMiMu
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.kyberix.OrMiMuUITests
