name: OrMiMu
options:
  bundleIdPrefix: dev.mfdogalindo
  deploymentTarget:
    macOS: "14.2"
  xcodeVersion: "15.0"
  groupSortPosition: top

targets:
  OrMiMu:
    type: application
    platform: macOS
    sources:
      - path: OrMiMu
        excludes:
          - Info.plist
          - OrMiMu.entitlements
      - path: OrMiMu/Info.plist
        type: file
      - path: OrMiMu/OrMiMu.entitlements
        type: file
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: dev.mfdogalindo.OrMiMu
      INFOPLIST_FILE: OrMiMu/Info.plist
      CODE_SIGN_ENTITLEMENTS: OrMiMu/OrMiMu.entitlements
      GENERATE_INFOPLIST_FILE: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_VERSION: 5.0
      SWIFT_STRICT_CONCURRENCY: complete
      ENABLE_HARDENED_RUNTIME: YES
      base:
        PRODUCT_NAME: OrMiMu
    postCompileScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint

  OrMiMuTests:
    type: bundle.unit-test
    platform: macOS
    sources: [OrMiMuTests]
    dependencies:
      - target: OrMiMu

  OrMiMuUITests:
    type: bundle.ui-testing
    platform: macOS
    sources: [OrMiMuUITests]
    dependencies:
      - target: OrMiMu
